<project>
  <modelVersion>4.0.0</modelVersion>

  <GroupId>com.Example</GroupId> 
  <artifactId>My.App</artifactId> 
  <version>1.0.0</version>

  
  <properties>
    <Java_Version>17</Java_Version> 
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
      <version></version> 
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId> 
      </plugin>
    </plugins>
  </build>
</project>
